apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
  name: npl-enabled
spec:
  adminCredentialRef:
    name: avi-controller-credentials
    namespace: tkg-system-networking
  certificateAuthorityRef:
    name: avi-controller-ca
    namespace: tkg-system-networking
  cloudName: vcsa-cs-w-01.lab.livefire.dev
  clusterSelector:
    matchLabels:
      npl-enabled: "true"
  controlPlaneNetwork:
    cidr: 172.25.10.0/23
    name: TKGm-vip-net-cl01-vds01
  controller: avic-02.lab.livefire.dev
  dataNetwork:
    cidr: 172.25.10.0/23
    name: TKGm-vip-net-cl01-vds01
  extraConfigs:
    cniPlugin: antrea               # required
    disableStaticRouteSync: false
    ingress:
      disableIngressClass: false
      nodeNetworkList:
        - cidrs:
          - 172.25.10.0/23
          networkName: TKGm-vip-net-cl01-vds01
      serviceType: NodePortLocal    # required
      shardVSSize: MEDIUM
  serviceEngineGroup: tkgm-se-group